# Generated by Django 5.2.5 on 2025-08-20 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên giáo phận')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã giáo phận')),
                ('bishop', models.CharField(blank=True, max_length=100, verbose_name='Giám mục')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('patron_saint', models.CharField(blank=True, max_length=100, verbose_name='Thánh bảo trợ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giáo phận',
                'verbose_name_plural': 'Giáo phận',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên giáo xứ')),
                ('code', models.CharField(max_length=20, verbose_name='Mã giáo xứ')),
                ('pastor', models.CharField(blank=True, max_length=100, verbose_name='Linh mục quản xứ')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('patron_saint', models.CharField(blank=True, max_length=100, verbose_name='Thánh bảo trợ')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Ngày thành lập')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='church_structure.diocese', verbose_name='Giáo phận')),
            ],
            options={
                'verbose_name': 'Giáo xứ',
                'verbose_name_plural': 'Giáo xứ',
                'ordering': ['diocese', 'name'],
                'unique_together': {('name', 'diocese')},
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên giáo họ')),
                ('leader', models.CharField(blank=True, max_length=100, verbose_name='Trưởng giáo họ')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='church_structure.parish', verbose_name='Giáo xứ')),
            ],
            options={
                'verbose_name': 'Giáo họ',
                'verbose_name_plural': 'Giáo họ',
                'ordering': ['parish', 'name'],
                'unique_together': {('name', 'parish')},
            },
        ),
    ]
