# Generated by Django 5.2.5 on 2025-08-18 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('entry_year', models.IntegerField(verbose_name='Entry Year')),
                ('current_year', models.IntegerField(choices=[(1, 'Năm thứ nhất'), (2, 'Năm thứ hai'), (3, 'Năm thứ ba'), (4, 'Năm thứ tư'), (5, 'Năm thứ năm'), (6, 'Năm thứ sáu')], verbose_name='Current Year')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('suspended', 'Tạm dừng'), ('graduated', 'Đã tốt nghiệp'), ('dropped', 'Đã thôi học')], default='active', max_length=20, verbose_name='Status')),
                ('hometown', models.CharField(max_length=100, verbose_name='Hometown')),
                ('family_situation', models.TextField(blank=True, verbose_name='Family Situation')),
                ('previous_education', models.TextField(blank=True, verbose_name='Previous Education')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Baptism Date')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('baptism_priest', models.CharField(blank=True, max_length=100, verbose_name='Baptism Priest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baptism_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baptized_students', to='church_structure.parish', verbose_name='Baptism Parish')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_structure.community', verbose_name='Community')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_structure.parish', verbose_name='Parish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('academic', 'Học tập'), ('behavior', 'Hạnh kiểm'), ('spiritual', 'Tâm linh'), ('health', 'Sức khỏe'), ('general', 'Chung')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
