# Generated by Django 5.2.5 on 2025-09-12 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('position', models.CharField(choices=[('rector', 'Rector'), ('vice_rector', 'Vice Rector'), ('spiritual_director', 'Spiritual Director'), ('professor', 'Professor'), ('lecturer', 'Lecturer')], max_length=50, verbose_name='Position')),
                ('education_background', models.TextField(blank=True, verbose_name='Educational Background')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization')),
                ('experience', models.TextField(blank=True, verbose_name='Work Experience')),
                ('office_room', models.CharField(blank=True, max_length=50, verbose_name='Office Room')),
                ('consultation_hours', models.TextField(blank=True, verbose_name='Consultation Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
            },
        ),
    ]
