# Generated by Django 5.2.5 on 2025-08-20 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Năm học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Năm học hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Năm học',
                'verbose_name_plural': 'Năm học',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('fall', 'Học kỳ I'), ('spring', 'Học kỳ II'), ('summer', 'Học kỳ hè')], max_length=20, verbose_name='Học kỳ')),
                ('class_code', models.CharField(max_length=20, verbose_name='Mã lớp')),
                ('max_students', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số sinh viên tối đa')),
                ('schedule', models.JSONField(blank=True, default=list, verbose_name='Lịch học')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Phòng học chính')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu đăng ký')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn đăng ký')),
                ('status', models.CharField(choices=[('planning', 'Đang lập kế hoạch'), ('open_registration', 'Mở đăng ký'), ('in_progress', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='planning', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('attendance_required', models.BooleanField(default=True, verbose_name='Bắt buộc điểm danh')),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Trọng số giữa kỳ (%)')),
                ('final_weight', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Trọng số cuối kỳ (%)')),
                ('assignment_weight', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Trọng số bài tập (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.academicyear', verbose_name='Năm học')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='teachers.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['-academic_year', 'semester', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('type', models.CharField(choices=[('homework', 'Bài tập về nhà'), ('essay', 'Tiểu luận'), ('presentation', 'Thuyết trình'), ('project', 'Đồ án'), ('quiz', 'Kiểm tra nhỏ'), ('research', 'Nghiên cứu')], max_length=20, verbose_name='Loại bài tập')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao')),
                ('due_date', models.DateTimeField(verbose_name='Hạn nộp')),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Điểm tối đa')),
                ('weight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Trọng số (%)')),
                ('instruction_file', models.FileField(blank=True, upload_to='assignments/instructions/', verbose_name='File hướng dẫn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Bài tập',
                'verbose_name_plural': 'Bài tập',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('name', models.CharField(max_length=200, verbose_name='Tên môn học')),
                ('english_name', models.CharField(blank=True, max_length=200, verbose_name='Tên tiếng Anh')),
                ('category', models.CharField(choices=[('theology', 'Thần học'), ('philosophy', 'Triết học'), ('scripture', 'Kinh thánh'), ('liturgy', 'Phụng vụ'), ('canon_law', 'Luật tắc'), ('pastoral', 'Mục vụ'), ('church_history', 'Lịch sử Giáo hội'), ('moral_theology', 'Luân lý thần học'), ('spirituality', 'Tâm linh học'), ('catechetics', 'Giáo lý học'), ('languages', 'Ngoại ngữ'), ('general', 'Giáo dục chung')], max_length=50, verbose_name='Loại môn học')),
                ('level', models.CharField(choices=[('basic', 'Cơ bản'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao'), ('specialized', 'Chuyên sâu')], default='basic', max_length=20, verbose_name='Trình độ')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số tín chỉ')),
                ('theory_hours', models.IntegerField(default=0, verbose_name='Giờ lý thuyết')),
                ('practice_hours', models.IntegerField(default=0, verbose_name='Giờ thực hành')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Mục tiêu học tập')),
                ('is_required', models.BooleanField(default=True, verbose_name='Môn bắt buộc')),
                ('year_taught', models.IntegerField(blank=True, choices=[(1, 'Năm thứ nhất'), (2, 'Năm thứ hai'), (3, 'Năm thứ ba'), (4, 'Năm thứ tư'), (5, 'Năm thứ năm'), (6, 'Năm thứ sáu')], null=True, verbose_name='Năm học dạy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn giảng dạy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.subject', verbose_name='Môn tiên quyết')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['category', 'year_taught', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject', verbose_name='Môn học'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày học')),
                ('session_number', models.IntegerField(verbose_name='Buổi học số')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi trễ'), ('excused', 'Vắng có phép')], max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người điểm danh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Chủng sinh')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.course', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'ordering': ['-date', 'session_number'],
                'unique_together': {('course', 'student', 'date', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('assignment_scores', models.JSONField(blank=True, default=list, verbose_name='Điểm bài tập')),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm giữa kỳ')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm cuối kỳ')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm tổng kết')),
                ('letter_grade', models.CharField(blank=True, max_length=5, verbose_name='Điểm chữ')),
                ('attendance_count', models.IntegerField(default=0, verbose_name='Số buổi có mặt')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Tổng số buổi học')),
                ('participation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm tham gia')),
                ('status', models.CharField(choices=[('enrolled', 'Đang học'), ('completed', 'Hoàn thành'), ('failed', 'Không đạt'), ('withdrawn', 'Rút môn'), ('suspended', 'Tạm dừng')], default='enrolled', max_length=20, verbose_name='Trạng thái')),
                ('withdrawal_reason', models.TextField(blank=True, verbose_name='Lý do rút môn')),
                ('instructor_notes', models.TextField(blank=True, verbose_name='Ghi chú của giảng viên')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Chủng sinh')),
            ],
            options={
                'verbose_name': 'Đăng ký học',
                'verbose_name_plural': 'Đăng ký học',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'academic_year', 'semester', 'class_code')},
        ),
    ]
